Update go to 1.20 & all go dependencies to latest
go mod tidy done as well, whole vendor folder updated.
The go1.20 bump is required due to:

```
$ go build
vendor/go.uber.org/multierr/error.go:224:20: undefined: atomic.Bool
note: module requires Go 1.19
```